import { useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { RoleDetails, GeneratedRecruitmentData } from "@/src/types";
import { generateRecruitmentContent } from "@/src/services/gemini";
import RoleInputForm from "./RoleInputForm";
import JDView from "./JDView";
import CriteriaView from "./CriteriaView";
import InterviewView from "./InterviewView";
import RubricView from "./RubricView";
import { FileText, Search, MessageSquare, BarChart3, ArrowLeft, Download, Share2 } from "lucide-react";
import { toast } from "sonner";

export default function RecruitmentDashboard() {
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<GeneratedRecruitmentData | null>(null);
  const [activeTab, setActiveTab] = useState("jd");

  const handleGenerate = async (details: RoleDetails) => {
    setIsLoading(true);
    try {
      const data = await generateRecruitmentContent(details);
      setResult(data);
      toast.success("Recruitment package generated successfully!");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate content. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleReset = () => {
    setResult(null);
    setActiveTab("jd");
  };

  if (!result) {
    return (
      <div className="min-h-screen bg-zinc-50 py-12 px-4">
        <RoleInputForm onSubmit={handleGenerate} isLoading={isLoading} />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="sticky top-0 z-10 bg-white border-b border-zinc-200 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={handleReset}>
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-xl font-bold tracking-tight">Recruitment Package</h1>
              <p className="text-xs text-zinc-500 uppercase font-semibold tracking-widest">Generated by HireSmart AI</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" className="hidden sm:flex" onClick={() => toast.info("Download feature coming soon!")}>
              <Download className="w-4 h-4 mr-2" />
              Export PDF
            </Button>
            <Button variant="outline" size="sm" className="hidden sm:flex" onClick={() => toast.info("Share feature coming soon!")}>
              <Share2 className="w-4 h-4 mr-2" />
              Share
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-6 py-8">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-8">
          <div className="flex justify-center">
            <TabsList className="grid grid-cols-4 w-full max-w-2xl h-12 p-1 bg-zinc-100 rounded-xl">
              <TabsTrigger value="jd" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm">
                <FileText className="w-4 h-4 mr-2" />
                <span className="hidden sm:inline">Job Description</span>
                <span className="sm:hidden">JD</span>
              </TabsTrigger>
              <TabsTrigger value="criteria" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm">
                <Search className="w-4 h-4 mr-2" />
                <span className="hidden sm:inline">Screening</span>
                <span className="sm:hidden">Criteria</span>
              </TabsTrigger>
              <TabsTrigger value="interview" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm">
                <MessageSquare className="w-4 h-4 mr-2" />
                <span className="hidden sm:inline">Interview</span>
                <span className="sm:hidden">Questions</span>
              </TabsTrigger>
              <TabsTrigger value="rubric" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm">
                <BarChart3 className="w-4 h-4 mr-2" />
                <span className="hidden sm:inline">Rubric</span>
                <span className="sm:hidden">Rubric</span>
              </TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="jd" className="mt-0 focus-visible:outline-none">
            <JDView data={result.jobDescription} />
          </TabsContent>
          <TabsContent value="criteria" className="mt-0 focus-visible:outline-none">
            <CriteriaView criteria={result.screeningCriteria} compliance={result.complianceCheck} />
          </TabsContent>
          <TabsContent value="interview" className="mt-0 focus-visible:outline-none">
            <InterviewView questions={result.interviewQuestions} />
          </TabsContent>
          <TabsContent value="rubric" className="mt-0 focus-visible:outline-none">
            <RubricView rubric={result.evaluationRubric} />
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
}
